// Generated by gencpp from file drivers/CaptureImageRequest.msg
// DO NOT EDIT!


#ifndef DRIVERS_MESSAGE_CAPTUREIMAGEREQUEST_H
#define DRIVERS_MESSAGE_CAPTUREIMAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drivers
{
template <class ContainerAllocator>
struct CaptureImageRequest_
{
  typedef CaptureImageRequest_<ContainerAllocator> Type;

  CaptureImageRequest_()
    {
    }
  CaptureImageRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::drivers::CaptureImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drivers::CaptureImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CaptureImageRequest_

typedef ::drivers::CaptureImageRequest_<std::allocator<void> > CaptureImageRequest;

typedef boost::shared_ptr< ::drivers::CaptureImageRequest > CaptureImageRequestPtr;
typedef boost::shared_ptr< ::drivers::CaptureImageRequest const> CaptureImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drivers::CaptureImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drivers::CaptureImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drivers::CaptureImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drivers::CaptureImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drivers::CaptureImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drivers::CaptureImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drivers::CaptureImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drivers::CaptureImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drivers::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::drivers::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::drivers::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drivers/CaptureImageRequest";
  }

  static const char* value(const ::drivers::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drivers::CaptureImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::drivers::CaptureImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drivers::CaptureImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaptureImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drivers::CaptureImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::drivers::CaptureImageRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DRIVERS_MESSAGE_CAPTUREIMAGEREQUEST_H
