// Generated by gencpp from file drivers/ServoResponse.msg
// DO NOT EDIT!


#ifndef DRIVERS_MESSAGE_SERVORESPONSE_H
#define DRIVERS_MESSAGE_SERVORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drivers
{
template <class ContainerAllocator>
struct ServoResponse_
{
  typedef ServoResponse_<ContainerAllocator> Type;

  ServoResponse_()
    : success(false)
    , message()
    , angle(0.0)  {
    }
  ServoResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::drivers::ServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drivers::ServoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServoResponse_

typedef ::drivers::ServoResponse_<std::allocator<void> > ServoResponse;

typedef boost::shared_ptr< ::drivers::ServoResponse > ServoResponsePtr;
typedef boost::shared_ptr< ::drivers::ServoResponse const> ServoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drivers::ServoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drivers::ServoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drivers::ServoResponse_<ContainerAllocator1> & lhs, const ::drivers::ServoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drivers::ServoResponse_<ContainerAllocator1> & lhs, const ::drivers::ServoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drivers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drivers::ServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drivers::ServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drivers::ServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drivers::ServoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drivers::ServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drivers::ServoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drivers::ServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "861bf17e2686cee0227971b17a17e4b7";
  }

  static const char* value(const ::drivers::ServoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x861bf17e2686cee0ULL;
  static const uint64_t static_value2 = 0x227971b17a17e4b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::drivers::ServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drivers/ServoResponse";
  }

  static const char* value(const ::drivers::ServoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drivers::ServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"float32 angle\n"
;
  }

  static const char* value(const ::drivers::ServoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drivers::ServoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drivers::ServoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drivers::ServoResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVERS_MESSAGE_SERVORESPONSE_H
